yarnPath: .yarn/releases/yarn-4.6.0.cjs

# Add this section to handle platform-specific dependencies
supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64

# Ensure consistent install behavior
nodeLinker: node-modules
